{
  parserClass="com.verilang.parser.VerilogParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Verilog"
  psiImplClassSuffix="Impl"
  psiPackage="com.verilang.psi"
  psiImplPackage="com.verilang.psi.impl"

  elementTypeHolderClass="com.verilang.psi.VerilogTypes"
  elementTypeClass="com.verilang.psi.VerilogElementType"
  tokenTypeClass="com.verilang.psi.VerilogTokenType"
}

verilogFile ::= MODULE character* ENDMODULE

private character ::= INPUT_CHARACTER

private comment ::= COMMENT
